name: Cypress Tests with Allure Report

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: automation/web/cypress
        run: npm install

      - name: Run Cypress tests
        working-directory: automation/web/cypress
        run: npm run cy:run

      - name: Generate Allure report
        working-directory: automation/web/cypress
        run: npm run allure:generate

      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Download Allure report
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report