name: allure-report
on:
    workflow_dispatch:
    push:
        branches:
            - main
    schedule:
    - cron: '0 9 * * *'   # todo dia às 09:00 UTC
    
jobs:
    generate-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              working-directory: automation/web/cypress
              env:
                CYPRESS_INSTALL_BINARY: 0
              run: npm ci

            - name: Check Cypress cache
              working-directory: automation/web/cypress
              run: |
                  npx cypress cache path
                  npx cypress cache list

            - name: restore / cache the binary
              id: cache-cypress
              uses: actions/cache@v3
              with:
                  path: ~/.cache/Cypress
                  key: cypress-cache-v2-${{ runner.os }}-${{ hashFiles('automation/web/cypress/package-lock.json') }}
                  restore-keys: |
                      cypress-cache-v2-${{ runner.os }}-
                      cypress-cache-v2-

            - name: Install Cypress
              working-directory: automation/web/cypress
              run: |
                  npx cypress install
                  npx cypress cache list

            - name: Run Cypress
              working-directory: automation/web/cypress
              continue-on-error: true
              if: always()
              run: npm run cy:run

            - name: Get Allure history
              uses: actions/checkout@v4
              if: always()
              continue-on-error: true
              with:
                  ref: allure
                  path: allure

            - name: Generate Allure Report
              uses: simple-elf/allure-report-action@master
              if: always()
              with:
                allure_results: automation/web/cypress/allure-results
                allure_report: allure-report
                allure_history: allure-history

            - name: Deploy report to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              if: always()
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_branch: allure
                publish_dir: allure-history