name: api-tests-newman

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'

permissions:
  contents: read

jobs:
  newman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman

      - name: Install HTML reporter (optional)
        run: npm install -g newman-reporter-html

      - name: Run Postman collection with Newman
        run: |
          newman run ./api-tests/postman/collections/serverest.json \
            -e ./api-tests/postman/environments/environments.json \
            --reporters cli,html \
            --reporter-html-export newman-report.html

      - name: Upload Newman report artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: newman-report.html